# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-06 07:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0002_auto_20170613_0939'),
    ]

    operations = [
        migrations.AddField(
            model_name='dinner',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=b''),
        ),
    ]
