# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-29 05:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_basket_basketitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='created',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='basket',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='basket',
            name='sum',
            field=models.FloatField(default=0),
        ),
    ]
