# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-27 05:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20170726_2046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='house',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
