# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-01 04:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_basket_route_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='city',
        ),
        migrations.RemoveField(
            model_name='address',
            name='house',
        ),
        migrations.RemoveField(
            model_name='address',
            name='street',
        ),
    ]
