# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-03 06:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_smscode'),
    ]

    operations = [
        migrations.RenameField(
            model_name='smscode',
            old_name='created',
            new_name='modified',
        ),
        migrations.AlterField(
            model_name='basket',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='smscode',
            name='sms_code',
            field=models.IntegerField(null=True),
        ),
    ]
